theme: jekyll-theme-cayman
# Setup
title: '3D Vision Research Group'
url: https://fanhao.github.io
# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
